site_name: Linux to Windows Guide
site_url: https://one-luke.github.io/site
theme:
  name: material
markdown_extensions:
  - admonition
nav:
  - 1. Overview: index.md
  - 2. Installation: installing.md
  - 3. Linux Commands: commands.md
  - 4. Customization: customization.md

  